# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pro < Formula
  desc ""
  homepage "https://github.com/wowu/pro"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Wowu/pro/releases/download/v0.2.0/pro-darwin-amd64"
      sha256 "b1ca54c662dd0f579699820e349b4c0f129cafd3b9ebdc772a9348a2d8cee258"

      def install
        bin.install "pro-darwin-amd64" => "pro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Wowu/pro/releases/download/v0.2.0/pro-darwin-arm64"
      sha256 "84c431def3fbb63db64b3159f51498bfc0ced777ef08640a8fd08398be9602ad"

      def install
        bin.install "pro-darwin-arm64" => "pro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Wowu/pro/releases/download/v0.2.0/pro-linux-amd64"
      sha256 "da96222a09c5fb26fe80e4f73161515f3d3467969674d5c3736c9945461b87ee"

      def install
        bin.install "pro-linux-amd64" => "pro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Wowu/pro/releases/download/v0.2.0/pro-linux-arm64"
      sha256 "ed1e5addfcea26d6d6edb860851fac7e8c35f584b385a95db37ae84f040b7035"

      def install
        bin.install "pro-linux-arm64" => "pro"
      end
    end
  end
end
