# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pro < Formula
  desc ""
  homepage "https://github.com/wowu/pro"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Wowu/pro/releases/download/v0.3.1/pro-darwin-arm64"
      sha256 "9c72fa51aa8239363a3ec00d501bb02cd00892d48fe40f64c854ba951957a46a"

      def install
        bin.install "pro-darwin-arm64" => "pro"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Wowu/pro/releases/download/v0.3.1/pro-darwin-amd64"
      sha256 "a1f3f27ae3a6a65485b4dd0fed8dcfd683778986953172a43b25589d6c790be4"

      def install
        bin.install "pro-darwin-amd64" => "pro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Wowu/pro/releases/download/v0.3.1/pro-linux-amd64"
      sha256 "066ae192da6e23b1cfae11a5adb34ea25502b431be3f5e3315bd395f3d0515d7"

      def install
        bin.install "pro-linux-amd64" => "pro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Wowu/pro/releases/download/v0.3.1/pro-linux-arm64"
      sha256 "a991aba5f2ca8ed6f58a2befe8f05635b33e96387afa724a4052c95201ae81df"

      def install
        bin.install "pro-linux-arm64" => "pro"
      end
    end
  end
end
